### PR TITLE
Execution workflows: Add per-PAS relative usage quantification BED file to APAtrap execution workflow

### LINKED ISSUE #416: Execution workflow: APAtrap - report Format 04 BED file in workflow (per-PAS fractional relative usage)
Parent issue - #382 

APAtrap's original absolute TPM quantification output for control_r1 looks like the following:
Screen Shot 2022-08-24 at 5 53 32 AM
For each transcript id, we have a list of all identified PAS and their expression levels from the most proximal to most distal if the strand is +, and the opposite for a - strand (source: [APAtrap wiki](https://sourceforge.net/p/apatrap/wiki/User%20Manual/)). 

The raw output above is then transformed into the following quantification output file:
Screen Shot 2022-08-30 at 8 28 09 PM

To get relative usage output, we would get each PAS in the transcript divided by the total sum of expression levels of all the PAS in the same transcript. For example, the screenshot above of the original output would be converted to the following:
Screen Shot 2022-08-30 at 8 27 34 PM

Taking the example of ENSMUST00000023572.14, from the quantification output file, we get the following:
```
ENSMUST00000023572.14|16|78336188-78340752|+    0.0
ENSMUST00000023572.14|16|78336188-78340752|+    50.15
ENSMUST00000023572.14|16|78336188-78340752|+    35.57   
```

In the relative quantification output file, the score column of the corresponding rows become:
```
ENSMUST00000023572.14|16|78336188-78340752|+    0.0
ENSMUST00000023572.14|16|78336188-78340752|+    0.5850443303779748 
ENSMUST00000023572.14|16|78336188-78340752|+    0.4149556696220252
```

### PR DESCRIPTION
**Pull request by faricazjj**
Fixes #416

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated corresponding READMEs (if applicable)
- [x] My code follows the templates/style guidelines of the repository
- [x] In- and output formats comply with APAeval specifications
- [x] No parameters or file names are hardcoded
- [x] Results, logs or other output is not commited to the repository
- [x] I have tested my code

### CODE REVIEW

**Review by yuukiiwa — COMMENTED** [review]
Thanks, @faricazjj!! Looks good to me!!

**Review by yuukiiwa — APPROVED** [review]
Thanks, @faricazjj!! Looks good to me!!

**Comment by mrgazzara** [comment]
In the process of being the 2nd reviewer for this right now.

**Review by mrgazzara — APPROVED** [review]
Everything looks good to me with these updates!

**Pull request merged**
