### PR TITLE
SWF: Identification

### LINKED ISSUE #175: Summary workflow: I2 benchmark metrics calculation
Write scripts for calculating metrics:

I2: Sensitivity and False Discovery Rate (FDR) of RNAseq-based poly(A) site identification compared with ground truth (poly(A)-sites identified from orthogonal 3'end seq data)

### PR DESCRIPTION
**Pull request by ninsch3000**
## Notes to reviewers
most careful review needed on file `compute_metrics.py`, as that is where the identification specific calculations are introduced. I used #239 as inspiration, but ended up implementing most of it myself. Note that the required changes to `utils/apaeval/` had been already done in my previous PR #415.

Fixes #175 #300
Makes PR #239 obsolete, closing that one manually

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated corresponding READMEs (if applicable)
- [x] My code follows the templates/style guidelines of the repository
- [x] In- and output formats comply with APAeval specifications
- [x] No parameters or file names are hardcoded
- [x] Results, logs or other output is not commited to the repository
- [x] I have tested my code

### CODE REVIEW

**Comment by ninsch3000** [comment]
## Optional metrics missing
Several metrics from the [identification specification](https://github.com/iRNA-COSI/APAeval/blob/swf_ident_new/summary_workflows/identification/specification/I_benchmark_specification.md) haven't been implemented yet:   
* [ ] Percentage of genes with correctly identified number of PAS
* [ ] Proportions of PAS assigned to different genomic features

Not all suggested plots are created either.    
PLEASE updated this comment as needed. (more checklist items, etc)

**Review by faricazjj — APPROVED** [review]
@ninsch3000 thank you so much!! LGTM! :D

**Review by dominikburri — APPROVED** [review]
Thank you @ninsch3000!
I tested with the provided small test sample, it ran successfully. I guess it is the same test as for absolute quantification? 
I also ran `compute_metrics.py` on another sample and the values seem fine. I did not check very rigorously though.

I only have a comment regarding the rogue metrics, i.e. the lists of precision and recall in a dedicated json object. But as this is not needed right now I think it this PR is good to go. 
I will add a commit for this.

As we discussed in the meeting yesterday, I would open a new PR for the missing metrics and plots.

**Review by faricazjj — APPROVED** [review]
Thank you so much @dominikburri and @ninsch3000!! LGTM! :D

**Review by yuukiiwa — APPROVED** [review]
Thank you so much!! Looks good to me!!

**Pull request merged**
