### PR TITLE
feat: Conda environment for execution workflows

### LINKED ISSUE #59: incosistent envs for calls to snakemake nextflow
From earlier discussion the issue arised, that nextflow and snakemake are executed from different (incosistent) conda environments specifications.
To solve this I need to 

- [ ] Modify the snakemake.yml to environment.yml and add both snakemake and nextflow specific versions
- [ ] Replace the nextflow env from the templates

I can not find the conda env from which nextflow is triggered, can someone point it out? Is such an environment needed in the context of nextflow? @uniqueg @dominikburri @yuukiiwa

### PR DESCRIPTION
**Pull request by mkatsanto**
Fixes #59 

## Checklist

- [X] I have performed a self-review of my own code
- [X] My code follows the templates/style guidelines of the repository
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have tested my code

### CODE REVIEW

**Comment by ninsch3000** [comment]
Thanks @mkatsanto ! I'm just not convinced about the location of the file. Nobody would have the idea to look in docs/templates/snakemake/ if they are looking for an environment to develop nextflow workflows for APAeval in. Wouldn't it be possible to put it in the root folder and mention in the README to work within this env for all APAeval? @uniqueg please comment :)

**Comment by mkatsanto** [comment]
@ninsch3000  I think if you check the latest commit I moved  the file in the home directory.

**Review by uniqueg — APPROVED** [review]
Looks good to me

**Comment by FitzsimmonsCM** [comment]
@all-contributors please add @mkatsanto for code

**Review by dominikburri — DISMISSED** [review]
Looks fine by me.

**Comment by ninsch3000** [comment]
Repeat: I'd really appreciate 2 lines in the "software" section of the main README on how to create and activate, and why to use the conda env? Thanks a lot!

**Review by dominikburri — DISMISSED** [review]
readme looks fine.

**Review by ninsch3000 — APPROVED** [review]

**Pull request merged**
