### PR TITLE
Quantification swf: additional metrics

### PR DESCRIPTION
**Pull request by dominikburri**
report binary classification metrics in `matchPAS.py`,
compute performance metrics (#324) and 
compute Jaccard index (#375) `compute_metrics.py`

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated corresponding READMEs (if applicable)
- [x] My code follows the templates/style guidelines of the repository
- [x] No parameters or file names are hardcoded
- [x] Results, logs or other output is not commited to the repository
- [x] I have tested my code

### CODE REVIEW

**Review by ninsch3000 — APPROVED** [review]
Not tested but LGTM. Thanks @dominikburri

**Comment by dominikburri** [comment]
Hi @ninsch3000, I just merged the latest main into the branch and tested again.
Let me know if the metric names are good and the string structure compatible with #381.
Then I can also add the names to `Q_benchmark_specification.md`.

**Comment by ninsch3000** [comment]
Hey @dominikburri good that you're asking, we need ":" in front of the window size instead of "_" in the metric names! Otherwise good!

**Comment by dominikburri** [comment]
> Hey @dominikburri good that you're asking, we need ":" in front of the window size instead of "_" in the metric names! Otherwise good!

Yes, sure, fixed it. Also added the names to the specs.

**Review by ninsch3000 — APPROVED** [review]

**Pull request merged**
